### ISSUE TITLE
NullPointerException because "shData" is null

### ISSUE THREAD

**Issue by headassbtw** [clienthax/Ps3GhidraScripts#22]
hey, installed all the things properly, decrypted the eboot, however whenever i try to run the script, it gives me this error:

```> Error running script: AnalyzePs3Binary.java
Cannot invoke "ghidra.program.model.listing.Data.getComponent(int)" because "shData" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Data.getComponent(int)" because "shData" is null
	at Ps3ElfUtils.parseSections(Ps3ElfUtils.java:124)
	at Ps3ElfUtils.<init>(Ps3ElfUtils.java:40)
	at AnalyzePs3Binary.run(AnalyzePs3Binary.java:28)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:395)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:250)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:228)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

---------------------------------------------------
Build Date: 2022-Nov-15 2224 CET
Ghidra Version: 10.2.2
Java Home: /usr/lib/jvm/java-19-openjdk
JVM Version: N/A 19.0.1
OS: Linux 6.0.11-zen1-1-zen amd64
```

any ideas? i even hit up a windows vm to try it, and the exact same error happened

**Comment by clienthax** [comment]
Can you attach the eboot?

**Comment by headassbtw** [comment]
yeah, [here](https://cdn.discordapp.com/attachments/860649179763441704/1058501708818436236/EBOOT.elf)

**Comment by headassbtw** [comment]
whoops, gaslit myself into thinking the PS3 was little endian

it is not.
