### ISSUE TITLE
the return value of "ghidra.program.model.listing.Data.getComponent(int)" is null

### ISSUE THREAD

**Issue by Lantern-r** [clienthax/Ps3GhidraScripts#24]
Whenever i try to run the script, it gives me this error:
```
Cannot invoke "ghidra.program.model.listing.Data.getLong(int)" because the return value of "ghidra.program.model.listing.Data.getComponent(int)" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Data.getLong(int)" because the return value of "ghidra.program.model.listing.Data.getComponent(int)" is null
	at Ps3ElfUtils.parseSections(Ps3ElfUtils.java:124)
	at Ps3ElfUtils.<init>(Ps3ElfUtils.java:40)
	at AnalyzePs3Binary.run(AnalyzePs3Binary.java:28)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:395)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:250)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:228)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by clienthax** [comment]
Need the elf

**Comment by Lantern-r** [comment]
[EBOOT.zip](https://github.com/clienthax/Ps3GhidraScripts/files/10927411/EBOOT.zip)

**Comment by clienthax** [comment]
What is this eboot from?, it seems non compliant with some assumptions the script has.

**Comment by Lantern-r** [comment]
This is a game in a CTF

**Comment by Hasster1** [comment]
Were you using small endian or big endian when selecting a language?
