### ISSUE TITLE
Reverse engineering stuff like 4.78 ps2_emu.elf/ps2_emu.self file

### ISSUE THREAD

**Issue by Onisatomimi-No-Miko** [clienthax/Ps3GhidraScripts#25]
Hello, is it possible for these scripts to reverse engineer stuff like ps2_emu.self (the PS3's original PS2 hardware emulator for CECHA/CECHB phat PS3)?

I've decrypted the available 4.78 OFW version of the ps2_emu.self found online with the appropriate ps3 keys to a proper .elf file, and then tried using AnalyzePs3Binary.java on the resulting ps2_emu.elf file using the most recent version of this repo's scripts (1.050) with the most recent version of Ghidra (ghidra_10.2.3) and the appropriate variation of the ghidra scripts (ghidra_10.2.3_PUBLIC_20230303_Ps3GhidraScripts.zip), but I end up gettng the following error log when I tried running AnalyzePS3Binary from the Code Browser's Script Manager:

```
AnalyzePs3Binary.java> Running...
e_shnum: 0xF
e_shentsize: 0x40
AnalyzePs3Binary.java> SECTION1
AnalyzePs3Binary.java> SECTION2
AnalyzePs3Binary.java> SECTION3
AnalyzePs3Binary.java> SECTION4
AnalyzePs3Binary.java> SECTION5
AnalyzePs3Binary.java> SECTION6
AnalyzePs3Binary.java> SECTION7
AnalyzePs3Binary.java> SECTION8
AnalyzePs3Binary.java> SECTION9
AnalyzePs3Binary.java> SECTION10
AnalyzePs3Binary.java> SECTION12
AnalyzePs3Binary.java> SECTION13
AnalyzePs3Binary.java> SECTION14
AnalyzePs3Binary.java> _elfHeader
AnalyzePs3Binary.java> _elfProgramHeaders
AnalyzePs3Binary.java> _elfSectionHeaders
section: addr=0x0 size=0x0
section: addr=0x0 size=0x180BF0
section: addr=0x180BF0 size=0x1A918
section: addr=0x19B508 size=0x12C0
section: addr=0x19C7C8 size=0x3F20
section: addr=0x1A06E8 size=0x200000
section: addr=0x3A06E8 size=0x10C580
section: addr=0x4ACC68 size=0x15CD0
section: addr=0x4C2938 size=0x20F88
section: addr=0x4E38C0 size=0x5FF0
section: addr=0x4E98B0 size=0xE060
section: addr=0x4F7910 size=0x0
section: addr=0x4F7910 size=0x20
section: addr=0x4F7930 size=0xB844C0
section: addr=0x0 size=0x78
AnalyzePs3Binary.java> Processing EXEC
e_entry: 4C2938
OPD: 4C2938
TOC: 100
AnalyzePs3Binary.java> Elf64_Ehdr
AnalyzePs3Binary.java> Couldn't find Elf64_Phdr[]

AnalyzePs3Binary.java> Reading PHDR array at null
> Error running script: AnalyzePs3Binary.java
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.address.Address.getAddressSpace()" because "addr" is null
	at ghidra.program.database.map.AddressMapDB.encodeRelative(AddressMapDB.java:612)
	at ghidra.program.database.map.AddressMapDB.getKey(AddressMapDB.java:268)
	at ghidra.program.database.code.CodeManager.getDefinedDataAt(CodeManager.java:1298)
	at ghidra.program.database.ListingDB.getDefinedDataAt(ListingDB.java:177)
	at ghidra.program.flatapi.FlatProgramAPI.getDataAt(FlatProgramAPI.java:1304)
	at AnalyzePs3Binary.applyProcessInfo(AnalyzePs3Binary.java:108)
	at AnalyzePs3Binary.handleExec(AnalyzePs3Binary.java:84)
	at AnalyzePs3Binary.process(AnalyzePs3Binary.java:99)
	at AnalyzePs3Binary.run(AnalyzePs3Binary.java:31)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:395)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:250)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:228)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by clienthax** [comment]
PS2 Emulators are outside the scope of intended use for the main script, they are alternative LV2 kernels that are used instead of GameOS,
IIRC they may also use 64bit addressing
