### ISSUE TITLE
Issue with EBOOT.BIN

### ISSUE THREAD

**Issue by cglmrfreeman** [clienthax/Ps3GhidraScripts#4]
Attempting to load an EBOOT.BIN from a recently released Skullgirls Pre-Alpha 0.1.9 build, I receive the following errors attempting to run the AnalyzePs3Binary.java script:

```
AnalyzePs3Binary.java> Running...
AnalyzePs3Binary.java> Well.. this shouldn't happen :|

AnalyzePs3Binary.java> Well.. this shouldn't happen :|

AnalyzePs3Binary.java> What the heck did you try and load!?
AnalyzePs3Binary.java> Finished!
```
Currently running Ghidra 9.2.1.

As an aside (and possibly related), I am also not seeing `PowerPC:BE:64:A2ALT-32addr:default` as a selection in the processor language list?

**Comment by aerosoul94** [comment]
I'm not so sure what went wrong with the error but..

Make sure that you uncheck this (also these 3 should pop up by default):
<img src="https://user-images.githubusercontent.com/12718188/103325861-5f61a180-4a13-11eb-9181-1c0d8a67fae8.png" width="400">

Then scroll down until you find this:
<img src="https://user-images.githubusercontent.com/12718188/103325878-6ee0ea80-4a13-11eb-9a37-94fb7f0da7cf.png" width="400">

Then you end up with this:
<img src="https://user-images.githubusercontent.com/12718188/103325893-8324e780-4a13-11eb-8078-025d14769f92.png" width="400">

**Comment by aerosoul94** [comment]
Actually, that message comes up when it fails to find the ELF header. Did you by chance forget to unpack it to an ELF file?

**Comment by cglmrfreeman** [comment]
> Actually, that message comes up when it fails to find the ELF header. Did you by chance forget to unpack it to an ELF file?

Ah, yeah, that was the major fail on my end. However, now after running AnalyzePs3Binary.java on the _ELF_ file, I get the following error
```
> Error running script: AnalyzePs3Binary.java
java.lang.NullPointerException
	at AnalyzePs3Binary.applyProcessInfo(AnalyzePs3Binary.java:205)
	at AnalyzePs3Binary.process(AnalyzePs3Binary.java:156)
	at AnalyzePs3Binary.run(AnalyzePs3Binary.java:71)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Additionally, AnalyzePs3Binary.java did not ask for nids.txt and DefinePs3Syscalls.java received the following error: `DefinePS3Syscalls.java> Couldnt find mapping for syscall_988`

**Comment by clienthax** [comment]
Send me the decrypted eboot clienthax@gmail.com

**Comment by clienthax** [comment]
Fixed by https://github.com/clienthax/Ps3GhidraScripts/commit/7d72232db311702244372f342a7e25e6d86b2112

**Comment by clienthax** [comment]
the syscall stuff is ignorable btw, it just means the name for that id isnt known
