### ISSUE TITLE
Error running script: AnalyzePs3Binary.java

### ISSUE THREAD

**Issue by Zarh** [clienthax/Ps3GhidraScripts#7]
I always have this error, I tryed with several EBOOT.elf

AnalyzePs3Binary.java> Running...
> Error running script: AnalyzePs3Binary.java
java.lang.NullPointerException
	at Ps3ElfUtils.findElfHeader(Ps3ElfUtils.java:46)
	at Ps3ElfUtils.<init>(Ps3ElfUtils.java:39)
	at AnalyzePs3Binary.run(AnalyzePs3Binary.java:28)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

I added r2, I set the language to PowerISA-Altivec-64-32addr (big endian)
I tryed with ghidra 9.2.2 and 10.0-BETA.
I have openJDK 11.0.1

Any idea of what I'm doing wrong ?

**Comment by clienthax** [comment]
Send me the elf, clienthax@gmail.com

**Comment by clienthax** [comment]
Did you install the plugin properly, or did you just add these scripts to your path?

**Comment by Zarh** [comment]
I installed the extention but I don't know how to launch it.... So, I launched your script from $HOME/ghidra_script
Maybe it's only working with extention ?

**Comment by clienthax** [comment]
It should show up in the script manager without being added as it's own path

**Comment by Zarh** [comment]
When I install the extension I select File > Install Extensions... Then I click on the "+", I select ghidra_9.2.2_PUBLIC_20210529_Ps3GhidraScripts.zip then it ask to restart ghidra.
The extension is installed at C:\Users\Zar\.ghidra\.ghidra_9.2.2_PUBLIC\Extensions\Ps3GhidraScripts
Inside there is 
- lib/Ps3GhidraScripts.jar  1kB
- Module.manifest    0 B
- Module.manifest.uninstalled 0 B
- README.md
The script aren't inside...

There is something I just noticed it seems I don't have the same version as you of ghidra, I have this one : https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip
I can't find yours, according to the name of the zip, it's ghidra_9.2.2_PUBLIC_20210529, I can't find it here : https://ghidra-sre.org/releaseNotes_9.2.4.html

**Comment by clienthax** [comment]
I've bumped the version we build the plugin for now incase thats the issue here.
Can you confirm that this is similar to what you see?
![image](https://user-images.githubusercontent.com/1056270/121232325-64136700-c889-11eb-96f2-e8bc38afe6bf.png)

After installing the extension it should be added to your scripts path automatically like so
![image](https://user-images.githubusercontent.com/1056270/121232761-d84e0a80-c889-11eb-9c49-b96226ca67e0.png)

**Comment by Zarh** [comment]
Thank you very much.

I'm finally able to install the extension. I used this version : https://ghidra-sre.org/ghidra_9.2.4_PUBLIC_20210427.zip with this one https://github.com/clienthax/Ps3GhidraScripts/releases/download/latest/ghidra_9.2.4_PUBLIC_20210608_Ps3GhidraScripts.zip

I can see the script. I launched it, it seems to work. (it didn't finish yet)

**Comment by Zarh** [comment]
Are the nid from the nids.txt the same as these : https://psdevwiki.com/ps3/VSH_Exports  ?
if yes, it look like some of them are missing.

Anyway thank you  very much ;)

**Comment by clienthax** [comment]
> Are the nid from the nids.txt the same as these : https://psdevwiki.com/ps3/VSH_Exports ?
> if yes, it look like some of them are missing.
> 
> Anyway thank you very much ;)

There's a lot from various firmware's etc and that page among other sources, I believe my nids file is the most complete list currently (I have a few more locally that I need to add it but they are mostly curl functions).

**Comment by Zarh** [comment]
After a second look, I made a mistake, sorry. I didn't search properly, for example I searched "0x45E124A" but in nids.txt it's "0x045E124A"

**Comment by clienthax** [comment]
> After a second look, I made a mistake, sorry. I didn't search properly, for example I searched "0x45E124A" but in nids.txt it's "0x045E124A"

Same value either way, nids.txt just uses the full hex value for simplifying lookups
